# Generated by Django 5.0.1 on 2024-02-27 09:59

import django.db.models.deletion
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_passwordreset'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='passwordreset',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='passwordreset',
            name='email',
        ),
        migrations.RemoveField(
            model_name='passwordreset',
            name='reset_code',
        ),
        migrations.AddField(
            model_name='passwordreset',
            name='token',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
        migrations.AddField(
            model_name='passwordreset',
            name='user',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='users.user'),
            preserve_default=False,
        ),
    ]
