# Generated by Django 5.0.1 on 2024-03-01 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_alter_user_options_alter_user_role_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={},
        ),
        migrations.AlterField(
            model_name='user',
            name='role_id',
            field=models.IntegerField(choices=[(1, 'Role 1'), (2, 'Role 2'), (3, 'Role 3'), (4, 'Role 4')]),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
