# Generated by Django 5.0.1 on 2024-03-14 05:23

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_remove_user_role_id_alter_user_user_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='permission',
            fields=[
                ('permission_id', models.AutoField(primary_key=True, serialize=False)),
                ('permission_name', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'permission',
            },
        ),
        migrations.CreateModel(
            name='role',
            fields=[
                ('role_id', models.AutoField(primary_key=True, serialize=False)),
                ('role_name', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'role',
            },
        ),
        migrations.CreateModel(
            name='RolePermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role_id', models.IntegerField()),
                ('permission_id', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='userPermission',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('user_id', models.IntegerField()),
                ('permission_id', models.IntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='role_id',
            field=models.IntegerField(choices=[(1, 'Role 1'), (2, 'Role 2'), (3, 'Role 3'), (4, 'Role 4')], default=4),  # Change the default value to the appropriate role ID
            preserve_default=False,
)

    ]