# Generated by Django 5.0.1 on 2024-03-14 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_permission_role_rolepermission_userpermission_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_name',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterModelTable(
            name='user',
            table='user',
        ),
    ]
