# Generated by Django 5.0.1 on 2024-03-14 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_alter_user_user_name_alter_user_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role_id',
            field=models.IntegerField(choices=[(4, 'Role 4')], default=4),
        ),
    ]
