# Generated by Django 5.0.1 on 2024-03-19 08:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0017_alter_permission_permission_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(unique=True)),
                ('description', models.CharField(max_length=100)),
                ('startdate', models.DateField()),
                ('enddate', models.DateField()),
                ('status', models.CharField(choices=[('TO-DO', 'To-Do'), ('IN-PROGRESS', 'In Progress'), ('COMPLETED', 'Completed')], default='TO-DO')),
                ('priority', models.CharField()),
                ('filemanagement', models.FileField(upload_to='project_files/')),
                ('image', models.ImageField(upload_to='project_query_files/')),
                ('projectmanager', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.user')),
            ],
            options={
                'db_table': 'project',
            },
        ),
        migrations.CreateModel(
            name='task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(unique=True)),
                ('description', models.CharField(max_length=100)),
                ('startdate', models.DateField()),
                ('enddate', models.DateField()),
                ('status', models.CharField(choices=[('TO-DO', 'To-Do'), ('IN-PROGRESS', 'In Progress'), ('COMPLETED', 'Completed')], default='TO-DO')),
                ('priority', models.CharField()),
                ('filemanagement', models.FileField(upload_to='task_files/')),
                ('image', models.ImageField(upload_to='task_query_files/')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.user')),
            ],
            options={
                'db_table': 'task',
            },
        ),
    ]
