# Generated by Django 5.0.1 on 2024-03-19 09:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0018_project_task'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='user',
        ),
        migrations.DeleteModel(
            name='project',
        ),
        migrations.DeleteModel(
            name='task',
        ),
    ]
