# Generated by Django 5.0.1 on 2024-03-20 08:46

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0019_remove_task_user_delete_project_delete_task'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='id',
        ),
        migrations.AddField(
            model_name='user',
            name='user_id',
            field=models.AutoField( primary_key=True, serialize=False),
            preserve_default=False,
        ),
    ]
