# Generated by Django 5.0.1 on 2024-03-26 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0020_remove_user_id_user_user_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='folder',
            fields=[
                ('folder_id', models.AutoField(primary_key=True, serialize=False)),
                ('folder_name', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'folder',
            },
        ),
        migrations.CreateModel(
            name='project',
            fields=[
                ('project_id', models.AutoField(primary_key=True, serialize=False)),
                ('project_name', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=100)),
                ('startdate', models.DateField()),
                ('enddate', models.DateField()),
                ('projecmanager', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('TO-DO', 'to-do'), ('IN_PROGRESS', 'in progress'), ('COMPLETED', 'completed')], default='TO-DO', max_length=20)),
            ],
            options={
                'db_table': 'project',
            },
        ),
        migrations.CreateModel(
            name='subfolder',
            fields=[
                ('subfolder_id', models.AutoField(primary_key=True, serialize=False)),
                ('subfolder_name', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'subfolder',
            },
        ),
        migrations.CreateModel(
            name='workplace',
            fields=[
                ('workplace_id', models.AutoField(primary_key=True, serialize=False)),
                ('workplace_name', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'workplace',
            },
        ),
    ]
